"""
This type stub file was generated by pyright.
"""

from inquirer.render.console.base import BaseConsoleRender

class Checkbox(BaseConsoleRender):
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    @property
    def is_long(self): # -> bool:
        ...
    
    def get_options(self): # -> Generator[tuple[Any, Unknown, Unknown], None, None]:
        ...
    
    def process_input(self, pressed):
        ...
    


