"""
This type stub file was generated by pyright.
"""

from inquirer.render.console.base import BaseConsoleRender

class List(BaseConsoleRender):
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    @property
    def is_long(self): # -> bool:
        ...
    
    def get_options(self): # -> Generator[tuple[Any, Unknown | Literal[' '], Unknown], None, None]:
        ...
    
    def process_input(self, pressed): # -> None:
        ...
    
    def get_current_value(self): # -> Literal['']:
        ...
    


