version: '3'

services:
  postgres:
    image: cockroachdb/cockroach
    environment:
      - COCKROACH_USER=postgres
      - COCKROACH_PASSWORD=postgres
    ports:
      - 26257:26257
      - 8080:8080
    command: start-single-node
