FROM mcr.microsoft.com/devcontainers/python:0-3.10

# renovate: datasource=github-releases depName=python-poetry/poetry
ARG POETRY_VERSION=1.3.2
ENV POETRY_HOME=/opt/poetry
RUN curl --fail -sSL https://install.python-poetry.org/ | python -
ENV PATH=$PATH:${POETRY_HOME}/bin
