#!/usr/bin/env bash

set -e

if ! python -m alembic upgrade head; then
    python -m radio_db init-db
fi

python -m radio_db monitor &
sleep 60 &
wait -n
while true; do
    python -m radio_db update-playlists &
    wait -n
    sleep 86400 &
    wait -n
done
