"""0.2.0

Revision ID: 4066a299242c
Revises: 
Create Date: 2021-06-07 11:55:38.811895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4066a299242c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state',
    sa.Column('key', sa.Enum('SpotifyAuth', name='statekey'), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('playlist',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('station', sa.BigInteger(), nullable=True),
    sa.Column('type_', sa.Enum('Top', name='playlisttype'), nullable=True),
    sa.Column('spotify_uri', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['station'], ['station.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spotify_uri')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist')
    op.drop_table('state')
    # ### end Alembic commands ###
