"""
This type stub file was generated by pyright.
"""

from inquirer.render.console import ConsoleRender

class Render:
    def __init__(self, impl=...) -> None:
        ...
    
    def render(self, question, answers):
        ...
    


