"""
This type stub file was generated by pyright.
"""

"""Module that implements the questions types."""
class TaggedValue:
    def __init__(self, label, value) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self):
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __ne__(self, other) -> bool:
        ...
    


class Question:
    kind = ...
    def __init__(self, name, message=..., choices=..., default=..., ignore=..., validate=..., show_default=...) -> None:
        ...
    
    @property
    def ignore(self): # -> bool:
        ...
    
    @property
    def message(self): # -> str:
        ...
    
    @property
    def default(self): # -> str:
        ...
    
    @property
    def choices_generator(self): # -> Generator[TaggedValue | Unknown | str | Any | list[Unknown] | tuple[Unknown, ...] | set[Unknown], None, None]:
        ...
    
    @property
    def choices(self): # -> list[TaggedValue | Unknown | str | Any | list[Unknown] | tuple[Unknown, ...] | set[Unknown]]:
        ...
    
    def validate(self, current): # -> None:
        ...
    


class Text(Question):
    kind = ...
    def __init__(self, name, message=..., default=..., **kwargs) -> None:
        ...
    


class Password(Text):
    kind = ...
    def __init__(self, name, echo=..., **kwargs) -> None:
        ...
    


class Editor(Text):
    kind = ...


class Confirm(Question):
    kind = ...
    def __init__(self, name, default=..., **kwargs) -> None:
        ...
    


class List(Question):
    kind = ...
    def __init__(self, name, message=..., choices=..., default=..., ignore=..., validate=..., carousel=...) -> None:
        ...
    


class Checkbox(Question):
    kind = ...


ERROR_INVALID_NAME = ...
def is_pathname_valid(pathname): # -> bool:
    """
    `True` if the passed pathname is a valid pathname for the current OS;
    `False` otherwise.
    """
    ...

class Path(Text):
    ANY = ...
    FILE = ...
    DIRECTORY = ...
    kind = ...
    def __init__(self, name, default=..., path_type=..., exists=..., normalize_to_absolute_path=..., **kwargs) -> None:
        ...
    
    def validate(self, current):
        ...
    
    def normalize_value(self, value):
        ...
    


def question_factory(kind, *args, **kwargs): # -> Text | Editor | Password | Confirm | List | Checkbox | Path:
    ...

def load_from_dict(question_dict) -> Question:
    """Load one question from a dict.

    It requires the keys 'name' and 'kind'.

    Returns:
        The Question object with associated data.
    """
    ...

def load_from_list(question_list) -> list[Question]:
    """Load a list of questions from a list of dicts.

    It requires the keys 'name' and 'kind' for each dict.

    Returns:
        A list of Question objects with associated data.
    """
    ...

def load_from_json(question_json) -> list | dict:
    """Load Questions from a JSON string.

    Returns:
        A list of Question objects with associated data if the JSON
        contains a list or a Question if the JSON contains a dict.
    """
    ...

