"""
This type stub file was generated by pyright.
"""

from typing import Any, TypeVar


def text(message, render=..., **kwargs): # -> str:
    ...

def editor(message, render=..., **kwargs): # -> str:
    ...

def password(message, render=..., **kwargs): # -> str:
    ...

def confirm(message, render=..., **kwargs): # -> str:
    ...

T = TypeVar('T')

def list_input(message: str, choices: list[T | tuple[str, T]] , render: Any = ..., **kwargs: Any) -> T:
    ...

def checkbox(message, render=..., **kwargs): # -> str:
    ...

def path(message, render=..., **kwargs): # -> str:
    ...

